#!/usr/bin/env python3
"""Post-processor: strips 'Source(s): \\texttt{...}' sentences from the
generated appendix-table captions (internal filenames must not render in the
PDF) and emits a single auto-generated provenance index table mapping each
table label to its generating script and result files. Run AFTER
gen_appendix.py and gen_appendix2.py."""
import re, sys
from pathlib import Path
MAIN_NAME = sys.argv[1] if len(sys.argv) > 1 else "main_iclr2027.tex"; OUT_NAME = sys.argv[2] if len(sys.argv) > 2 else "tab_z_provenance.tex"; SUBDIR = sys.argv[3] if len(sys.argv) > 3 else ""   # final version: appendix_tables/final/, floating tables

TD = Path(__file__).parent / "appendix_tables" / SUBDIR if SUBDIR else Path(__file__).parent / "appendix_tables"
prov = []
pat = re.compile(r"\s*Sources?:\s*((?:\\texttt\{[^}]*\}(?:,\s*)?)+)\.?")

for f in sorted(TD.glob("tab_*.tex")):
    t = f.read_text()
    m_label = re.search(r"\\label\{([^}]*)\}", t)
    label = m_label.group(1) if m_label else f.stem
    m = pat.search(t)
    files = ""
    if m:
        files = ", ".join(re.findall(r"\\texttt\{([^}]*)\}", m.group(1)))
        t = pat.sub("", t)
        f.write_text(t)
    mp = re.search(r"^% prov: (.*)$", t, flags=re.M)      # final pass: consolidated tables declare their result files on one line
    if mp: files = mp.group(1).strip()
    prov.append((label, f.stem, files.replace("\\_", "_")))

lines = [r"\begin{table}[tbp]" if SUBDIR else r"\begin{table}[H]", r"\centering", r"\scriptsize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{ll>{\raggedright\arraybackslash}p{9.0cm}}", r"\toprule",
         r"table & generated file & result file(s) \\", r"\midrule"]
MAIN = (Path(__file__).parent / MAIN_NAME).read_text()
prov = [x for x in prov if (f"appendix_tables/{SUBDIR}/{x[1]}}}" if SUBDIR else f"appendix_tables/{x[1]}}}") in MAIN and not x[1].startswith("tab_z_provenance")]   # the closing brace: tab_q04_depth must not match tab_q04_depth_final  # index only tables the paper includes
for label, stem, files in prov:
    ftex = files.replace("_", r"\_") if files else "(stated in generator)"
    lines.append(rf"\ref{{{label}}} & \texttt{{{stem.replace('_', chr(92)+'_')}}} & {' '.join(chr(92)+'texttt{'+x.strip()+'}' for x in ftex.split(',')) if files else ftex} \\")
lines += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Provenance index: every table of this appendix is generated by script from the "
          r"result files listed here; no table value is hand-transcribed. The same mapping for "
          r"the main text is annotated in the source and shipped with the code release.}",
          r"\label{tab:provenance}", r"\end{table}"]
(TD/OUT_NAME).write_text("\n".join(lines) + "\n")
print(f"stripped+indexed {sum(1 for _,_,f in prov if f)} tables; provenance index written")
