#!/usr/bin/env python3
"""Post-processor: strips 'Source(s): \\texttt{...}' sentences from the
generated appendix-table captions (internal filenames must not render in the
PDF) and emits a single auto-generated provenance index table mapping each
table label to its generating script and result files. Run AFTER
gen_appendix.py and gen_appendix2.py."""
import re
from pathlib import Path

TD = Path(__file__).parent / "appendix_tables"
prov = []
pat = re.compile(r"\s*Sources?:\s*((?:\\texttt\{[^}]*\}(?:,\s*)?)+)\.?")

for f in sorted(TD.glob("tab_*.tex")):
    t = f.read_text()
    m_label = re.search(r"\\label\{([^}]*)\}", t)
    label = m_label.group(1) if m_label else f.stem
    m = pat.search(t)
    files = ""
    if m:
        files = ", ".join(re.findall(r"\\texttt\{([^}]*)\}", m.group(1)))
        t = pat.sub("", t)
        f.write_text(t)
    mp = re.search(r"^% prov: (.*)$", t, flags=re.M)      # final pass: consolidated tables declare their result files on one line
    if mp: files = mp.group(1).strip()
    prov.append((label, f.stem, files.replace("\\_", "_")))

lines = [r"\begin{table}[H]", r"\centering", r"\scriptsize", r"\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{ll>{\raggedright\arraybackslash}p{9.0cm}}", r"\toprule",
         r"table & generated file & result file(s) \\", r"\midrule"]
MAIN = (Path(__file__).parent / "main_iclr2027.tex").read_text()
prov = [x for x in prov if f"appendix_tables/{x[1]}" in MAIN and x[1] != "tab_z_provenance"]  # index only tables the paper includes
for label, stem, files in prov:
    ftex = files.replace("_", r"\_") if files else "(stated in generator)"
    lines.append(rf"\ref{{{label}}} & \texttt{{{stem.replace('_', chr(92)+'_')}}} & {' '.join(chr(92)+'texttt{'+x.strip()+'}' for x in ftex.split(',')) if files else ftex} \\")
lines += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Provenance index: every appendix table is generated by script from the "
          r"released per-cell result files listed here; no table value is hand-transcribed. "
          r"The same mapping for main-text tables and figures is annotated in the source and "
          r"shipped with the code release.}",
          r"\label{tab:provenance}", r"\end{table}"]
(TD/"tab_z_provenance.tex").write_text("\n".join(lines) + "\n")
print(f"stripped+indexed {sum(1 for _,_,f in prov if f)} tables; provenance index written")
