#!/usr/bin/env python3
"""expR68 (final pass, A3): the corollary's delta-gain correlations recomputed on the calibrated reading.

The corollary (Figure 11 = fig_bestmetric_scatter, Tables B5/B12) correlates the raw delta_norm with the metric gains.
Here every correlation is recomputed on the same cells (the 10 task-grid backbones x {ImageNet, CIFAR-100, CIFAR-10, DTD};
gains from exp2_metric_controls.csv / table1_regenerated.csv as in the generators) with three predictors:
  raw   : the raw census reading (expR52 delta_999, the same protocol as Table 1; the old figure used the same column),
  excess: the record excess (expR52),
  depth : the depth-test z (expR56, anisotropic star; ImageNet K=30, CIFAR-100 K=20; not defined on CIFAR-10/DTD).
Per dataset: Pearson r with a Fisher-z 95% CI (n = 10 models), and the family-demeaned r of Table B12 (both variables
centered within family). Gains: NC H-R, FS H-R, FS best-R (best of Poincare/cosine minus Euclidean). Output:
expR68_corollary_excess.csv; the figure is regenerated by make_figs.py from the same file."""
import csv, statistics as st, numpy as np, pandas as pd
from pathlib import Path
RES = Path(__file__).resolve().parents[1] / "results"
def load(f): return list(csv.DictReader(open(RES / f)))
rec = {(r["model"], r["dataset"]): r for r in load("expR52_census_haar_p999_200.csv")}
dv = {(r["model"], r["dataset"]): float(r["z_depth"]) for r in load("expR56_depth_variants.csv") if r["variant"] == "aniso" and ((r["dataset"] == "imagenet" and int(r["K"]) == 30) or (r["dataset"] == "cifar100" and int(r["K"]) == 20))}
t1 = {(r["model"], r["dataset"]): r for r in load("table1_regenerated.csv")}; e2 = {(r["model"], r["dataset"]): r for r in load("exp2_metric_controls.csv")}
models = sorted({m for m, _ in t1}); H = ["imagenet", "cifar100", "cifar10", "dtd"]
fam = lambda m: "ViT" if m.startswith("i21k") else ("DINOv2" if m.startswith("dinov2") else "CLIP")
def demean(vals, fams):
    mu = {f: st.mean(v for v, g in zip(vals, fams) if g == f) for f in set(fams)}; return [v - mu[g] for v, g in zip(vals, fams)]
def pear(x, y): return float(np.corrcoef(x, y)[0, 1])
def fisher_ci(r, n):
    if n < 4 or abs(r) >= 1: return (float("nan"), float("nan"))
    z = np.arctanh(r); se = 1 / np.sqrt(n - 3); return float(np.tanh(z - 1.96 * se)), float(np.tanh(z + 1.96 * se))
GAINS = {"NC_adv": lambda m, ds: float(t1[(m, ds)]["NC_adv"]), "FS_adv": lambda m, ds: float(t1[(m, ds)]["FS_adv"]),
         "FS_best_adv": lambda m, ds: 100 * (max(float(e2[(m, ds)]["FS_H"]), float(e2[(m, ds)]["FS_COS"])) - float(e2[(m, ds)]["FS_R"]))}
PRED = {"raw": lambda m, ds: float(rec[(m, ds)]["delta"]), "excess": lambda m, ds: float(rec[(m, ds)]["excess"]), "depth_z": lambda m, ds: dv.get((m, ds))}
rows = []
for pname, pf in PRED.items():
    for gname, gf in GAINS.items():
        for ds in H:
            pts = [(pf(m, ds), gf(m, ds), fam(m)) for m in models if pf(m, ds) is not None]
            if len(pts) < 4: continue
            x = [p[0] for p in pts]; y = [p[1] for p in pts]; f = [p[2] for p in pts]; r = pear(x, y); lo, hi = fisher_ci(r, len(pts))
            rows.append(dict(predictor=pname, gain=gname, dataset=ds, n=len(pts), r=r, ci_lo=lo, ci_hi=hi, r_demeaned=pear(demean(x, f), demean(y, f)),
                             **{f"r_{fm}": (pear([a for a, g in zip(x, f) if g == fm], [b for b, g in zip(y, f) if g == fm]) if sum(g == fm for g in f) >= 3 else float("nan")) for fm in ("ViT", "DINOv2", "CLIP")}))
        # pooled over the four hierarchical sets
        pts = [(pf(m, ds), gf(m, ds), fam(m)) for ds in H for m in models if pf(m, ds) is not None]
        x = [p[0] for p in pts]; y = [p[1] for p in pts]; f = [p[2] for p in pts]; r = pear(x, y); lo, hi = fisher_ci(r, len(pts))
        rows.append(dict(predictor=pname, gain=gname, dataset="pooled", n=len(pts), r=r, ci_lo=lo, ci_hi=hi, r_demeaned=pear(demean(x, f), demean(y, f)), r_ViT=float("nan"), r_DINOv2=float("nan"), r_CLIP=float("nan")))
df = pd.DataFrame(rows); df.to_csv(RES / "expR68_corollary_excess.csv", index=False)
old = {(r["task"], r["dataset"]): r for r in load("night/correlation_cis.csv")}
for gname in GAINS:
    for ds in H:
        o = old.get((gname, ds)); a = df[(df.predictor == "raw") & (df.gain == gname) & (df.dataset == ds)].iloc[0]; b = df[(df.predictor == "excess") & (df.gain == gname) & (df.dataset == ds)].iloc[0]
        z = df[(df.predictor == "depth_z") & (df.gain == gname) & (df.dataset == ds)]
        print(f"{gname:12s} {ds:9s} old-raw r {float(o['r']) if o else float('nan'):+.2f} | raw {a.r:+.2f} [{a.ci_lo:+.2f},{a.ci_hi:+.2f}] dm {a.r_demeaned:+.2f} | excess {b.r:+.2f} [{b.ci_lo:+.2f},{b.ci_hi:+.2f}] dm {b.r_demeaned:+.2f}" + (f" | depth z {z.iloc[0].r:+.2f} [{z.iloc[0].ci_lo:+.2f},{z.iloc[0].ci_hi:+.2f}]" if len(z) else ""))
print("DONE expR68")
