#!/usr/bin/env python3
"""README of the supplementary material (author's brief, 2026-09-24): the provenance table left the paper, so the mapping
table/figure -> script -> result file lives here. Everything is read from the built submission and the generated table files,
so the mapping cannot drift from the paper."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1].parent
TEX = ROOT / "ICLR2027" / "iclr2027"; FD = TEX / "appendix_tables" / "final"
T = (TEX / "main_iclr2027_final.tex").read_text()
OUT = ROOT / "ICLR2027" / "supplementary_code" / "README.md"
GEN = {"tab_q14_panel": "iclr2027/gen_appendix_final.py", "tab_khrulkov_final": "iclr2027/gen_appendix_final.py"}
num = {}
for m in re.finditer(r"\\(?:label)\{(tab:[^}]*)\}", T): num.setdefault(m.group(1), None)
rows = []
for f in sorted(FD.glob("tab_*.tex")) + [TEX / "tab_khrulkov_final.tex"]:
    src = f.read_text()
    if ("\\input{appendix_tables/final/" + f.stem + "}") not in T and ("\\input{" + f.stem + "}") not in T: continue
    prov = re.search(r"(?m)^% prov: (.*)$", src)
    files = [x.strip() for x in prov.group(1).split(",")] if prov else []
    labs = re.findall(r"\\label\{(tab:[^}]*)\}", src)
    if labs: rows.append((labs, GEN.get(f.stem, "iclr2027/gen_appendix_final.py"), files))
figs = []
for fb in re.findall(r"\\begin\{figure\}.*?\\end\{figure\}", T, flags=re.S):
    lab = re.search(r"\\label\{(fig:[^}]*)\}", fb); img = re.search(r"\\includegraphics\[[^\]]*\]\{figures/([^}]*)\.pdf\}", fb)
    src = re.findall(r"%\s*([^\n]*\.(?:csv|npz|json)[^\n]*)", fb)
    if lab: figs.append((lab.group(1), img.group(1) if img else "(drawn by the authors)", [x.strip() for x in (src[0].split(",") if src else [])]))
main_files = sorted({x for line in re.findall(r"(?m)(?<!\\)%(.*)$", T[:T.index("\\appendix")]) for x in re.findall(r"[\w/]+\.(?:csv|npz|json)", line)})
L = ["# Supplementary material: what produces every number", "",
     "The paper carries no hand-transcribed value. Every table and figure is written by a script from a result file in",
     "`results/`. This file is the mapping; it is regenerated by `scripts/make_supp_readme.py` from the built paper.", "",
     "## Pipeline", "",
     "1. `scripts/` runs the experiments and writes one CSV or JSON per experiment into `results/`.",
     "2. `iclr2027/gen_appendix_final.py` and `iclr2027/gen_main_table.py` write the appendix tables into `iclr2027/appendix_tables/final/`.",
     "3. `figures/make_figs_final.py` writes every figure into `figures/`.",
     "4. `scripts/phaseE_submission.py` assembles `iclr2027/main_iclr2027_final.tex`; `scripts/sweep_freeze.py` re-derives every number in it from the result files.", "",
     "## Tables", "", "| tables of the question | generator | result files |", "|---|---|---|"]
for labs, gen, files in rows: L.append("| " + ", ".join(f"`{l}`" for l in labs) + f" | `{gen}` | " + (", ".join(f"`{x}`" for x in files) if files else "(stated in the generator)") + " |")
L += ["", "## Figures", "", "| figure | script | result files |", "|---|---|---|"]
for lab, img, files in figs: L.append(f"| `{lab}` (`figures/{img}.pdf`) | `figures/make_figs_final.py` | " + (", ".join(f"`{x}`" for x in files) if files else "(drawn by the authors)") + " |")
L += ["", "## Result files behind the main text", "",
      "Every sentence of the main text carries its result file in a source comment. The files named there are:", ""]
L += ["- `" + f + "`" for f in main_files]
L += ["", f"({sum(len(r[0]) for r in rows)} tables, {len(figs)} figures, {len(main_files)} result files named in the main text.)"]
OUT.parent.mkdir(parents=True, exist_ok=True); OUT.write_text("\n".join(L) + "\n")
print(f"supplementary README written -> {OUT.relative_to(ROOT)}: {len(rows)} tables, {len(figs)} figures, {len(main_files)} result files")
