#!/usr/bin/env python3
"""Writes iclr2027/MEMO_phaseA.md from the Phase-A result files. Numbers only; no recommendations."""
import os, sys
import numpy as np, pandas as pd
from pathlib import Path
R = Path(os.environ.get("PLATONIC_RESULTS", str(Path(__file__).resolve().parents[1]/"results")))
OUTMD = Path(__file__).resolve().parents[2]/"iclr2027"/"MEMO_phaseA.md"
M = ["i21k_t","i21k_s","i21k_b","i21k_l","dinov1_b","dinov2_s","dinov2_b","dinov2_l","dinov2_g","clip_b","clip_l","siglip_b"]
NM = {"i21k_t":"ViT-T","i21k_s":"ViT-S","i21k_b":"ViT-B","i21k_l":"ViT-L","dinov1_b":"DINO-B","dinov2_s":"DINOv2-S","dinov2_b":"DINOv2-B",
      "dinov2_l":"DINOv2-L","dinov2_g":"DINOv2-G","clip_b":"CLIP-B","clip_l":"CLIP-L","siglip_b":"SigLIP-B"}
DS = ["imagenet","cifar100","cifar10","dtd","fashionmnist","mnist"]
FAM = {"sup": ["i21k_t","i21k_s","i21k_b","i21k_l"], "DINOv2": ["dinov2_s","dinov2_b","dinov2_l","dinov2_g"], "CLIP": ["clip_b","clip_l"]}
VIS = {"Haar x p99.9 (record)": "expR52_census_haar_p999_200.csv", "Haar x sup": "expR54_census_haar_sup_200.csv",
       "Gauss x p99.9": "expR40b_p999census200.csv", "Gauss x sup": "expR39c_census200_cache.csv"}
TXT = {"Haar x p99.9 (record)": "expR53_text_haar_p999_200.csv", "Haar x sup": "expR53_text_haar_sup_200.csv",
       "Gauss x p99.9": "expR53_text_gauss_p999_200.csv", "Gauss x sup": "expR48b_text_census200_bs1.csv"}
def bh(p):
    p = np.asarray(p, dtype=float); n = len(p); order = np.argsort(p); ranked = p[order]*n/np.arange(1, n+1)
    adj = np.minimum.accumulate(ranked[::-1])[::-1]; out = np.empty(n); out[order] = np.minimum(adj, 1.0); return out
def load(f):
    p = R/f
    if not p.exists(): return None
    df = pd.read_csv(p)
    if "p_left" not in df: return None
    if "p_bh" not in df: df["p_bh"] = bh(df.p_left.values)
    df["genuine"] = df.p_left <= 0.05; df["genuine_bh"] = df.p_bh <= 0.05
    return df
def counts(df):
    top = df[df.dataset.isin(["imagenet","cifar100"])]; rest = df[~df.dataset.isin(["imagenet","cifar100"])]
    return dict(sign=int((df.excess<0).sum()), gen=int(df.genuine.sum()), gen_bh=int(df.genuine_bh.sum()),
                top_bh=int(top.genuine_bh.sum()), rest_bh=int(rest.genuine_bh.sum()))
L = ["# MEMO Phase A — numbers only (generated by rebuttal/scripts/make_memo_phaseA.py)\n"]
# ---------- A1 vision 2x2 ----------
L.append("## A1. Vision census, 2x2 (null construction x statistic), 200 replicates, census cache\n")
L.append("| construction | sign-negative /72 | genuine (p<=0.05) /72 | genuine BH /72 | ImageNet+CIFAR-100 BH /24 | other four BH /48 |")
L.append("|---|---|---|---|---|---|")
dfs = {}
for name, f in VIS.items():
    df = load(f); dfs[name] = df
    if df is None: L.append(f"| {name} | (missing: {f}) | | | | |"); continue
    c = counts(df); L.append(f"| {name} | {c['sign']} | {c['gen']} | {c['gen_bh']} | {c['top_bh']} | {c['rest_bh']} |")
rec = dfs.get("Haar x p99.9 (record)")
if rec is not None:
    L.append("\n### Per-cell table, census of record (excess; r/200; p; BH-genuine)\n")
    L.append("| model | " + " | ".join(DS) + " |"); L.append("|---|" + "---|"*len(DS))
    by = {(r.model, r.dataset): r for r in rec.itertuples()}
    for m in M:
        cells = []
        for d in DS:
            r = by.get((m, d)); cells.append("--" if r is None else f"{r.excess:+.3f}; {int(r.r_above)}; {r.p_left:.3f}; {'G' if r.genuine_bh else '-'}")
        L.append(f"| {NM[m]} | " + " | ".join(cells) + " |")
    L.append("\n### Scale trend per family per transfer dataset under the record (excess S -> largest; monotone = strictly decreasing)\n")
    L.append("| family | dataset | excesses in size order | monotone? |"); L.append("|---|---|---|---|")
    for fam, ms in FAM.items():
        for d in ["cifar100","cifar10","dtd"]:
            xs = [by[(m, d)].excess for m in ms if (m, d) in by]
            mono = all(xs[i+1] < xs[i] for i in range(len(xs)-1))
            L.append(f"| {fam} | {d} | " + ", ".join(f"{x:+.3f}" for x in xs) + f" | {'yes' if mono else 'no'} |")
# DINOv2-S/B/G on ImageNet under all four
L.append("\n### DINOv2-S/B/G on ImageNet under the four constructions (excess; r/200; p; BH-genuine)\n")
L.append("| construction | DINOv2-S | DINOv2-B | DINOv2-G | DINOv2-L | DINO-B |"); L.append("|---|---|---|---|---|---|")
for name, df in dfs.items():
    if df is None: continue
    by = {(r.model, r.dataset): r for r in df.itertuples()}
    L.append(f"| {name} | " + " | ".join(f"{by[(m,'imagenet')].excess:+.3f}; {int(by[(m,'imagenet')].r_above)}; {by[(m,'imagenet')].p_left:.3f}; {'G' if by[(m,'imagenet')].genuine_bh else '-'}" for m in ["dinov2_s","dinov2_b","dinov2_g","dinov2_l","dinov1_b"]) + " |")
# ---------- A1 text 2x2 ----------
L.append("\n## A1. Text census, 2x2, 200 replicates, padding-free\n")
L.append("| construction | genuine (p<=0.05) /15 | genuine BH /15 | genuine models (BH) | GPT-2 S / M / L / XL: excess (p) |"); L.append("|---|---|---|---|---|")
for name, f in TXT.items():
    df = load(f)
    if df is None: L.append(f"| {name} | (missing: {f}) | | | |"); continue
    g = {r.model: r for r in df.itertuples()}
    gpt = " / ".join(f"{g[m].excess:+.3f} ({g[m].p_left:.3f})" for m in ["gpt2","gpt2_m","gpt2_l","gpt2_xl"] if m in g)
    L.append(f"| {name} | {int(df.genuine.sum())} | {int(df.genuine_bh.sum())} | {', '.join(df[df.genuine_bh].model)} | {gpt} |")
# ---------- bootstrap ----------
bs = R/"expR59_imagenet_bootstrap_summary.csv"
if bs.exists():
    b = pd.read_csv(bs); L.append("\n## A1. ImageNet centroid bootstrap under the record (30 resamples, 20 Haar replicates each)\n")
    L.append("| model | excess (reference) | bootstrap mean | bootstrap s.d. | fraction negative |"); L.append("|---|---|---|---|---|")
    for r in b.itertuples(): L.append(f"| {NM.get(r.model, r.model)} | {r.excess_ref:+.4f} | {r.excess_boot_mean:+.4f} | {r.excess_boot_sd:.4f} | {r.frac_boot_negative:.2f} |")
# ---------- A2 depth ----------
pw = R/"expR55_depth_power.csv"
if pw.exists():
    df = pd.read_csv(pw); h = df[df.level!="star"]; st = df[df.level=="star"]
    L.append("\n## A2. Depth-test power (synthetic; z<=-2 on hierarchies) and star false alarms (|z|>=2)\n")
    L.append("| n | K | power @ ratio 0.1 / 0.3 / 0.6 | hier2 / hier3 | iso / aniso | star false alarms (z<=-2 / z>=+2) |"); L.append("|---|---|---|---|---|---|")
    for n in (100, 1000):
        for K in (6, 12, 20, 30):
            hh = h[(h.n==n)&(h.K==K)]; ss = st[(st.n==n)&(st.K==K)]
            if len(hh)==0: continue
            L.append(f"| {n} | {K} | " + " / ".join(f"{(hh[hh.ratio==r].z<=-2).mean():.2f}" for r in (0.1,0.3,0.6)) +
                     f" | {(hh[hh.level=='hier2'].z<=-2).mean():.2f} / {(hh[hh.level=='hier3'].z<=-2).mean():.2f} | {(hh[hh.aniso=='iso'].z<=-2).mean():.2f} / {(hh[hh.aniso=='aniso'].z<=-2).mean():.2f} | {(ss.z<=-2).mean():.2f} / {(ss.z>=2).mean():.2f} |")
dv = R/"expR56_depth_variants.csv"
if dv.exists():
    df = pd.read_csv(dv); L.append("\n## A2. Matched-star depth test on the real backbones: isotropic (a) vs anisotropic (b) star, 10 star seeds, K sweep\n")
    L.append("| dataset | K | variant | mean depth | z<=-2 (depth) | z>=+2 (less tree-like than star) | max z | min z |"); L.append("|---|---|---|---|---|---|---|---|")
    for (ds, K, v), g in df.groupby(["dataset","K","variant"]):
        L.append(f"| {ds} | {K} | {v} | {g.depth_excess.mean():+.4f} | {int((g.z_depth<=-2).sum())}/{len(g)} | {int((g.z_depth>=2).sum())}/{len(g)} | {g.z_depth.max():+.1f} | {g.z_depth.min():+.1f} |")
    L.append("\nPer model at the paper's frames (CIFAR-100 K=20, ImageNet K=30): depth (z), iso -> aniso\n")
    L.append("| model | CIFAR-100 iso | CIFAR-100 aniso | ImageNet iso | ImageNet aniso |"); L.append("|---|---|---|---|---|")
    g = {(r.model, r.dataset, r.K, r.variant): r for r in df.itertuples()}
    for m in M:
        c = [g.get((m,"cifar100",20,"iso")), g.get((m,"cifar100",20,"aniso")), g.get((m,"imagenet",30,"iso")), g.get((m,"imagenet",30,"aniso"))]
        L.append(f"| {NM[m]} | " + " | ".join("--" if r is None else f"{r.depth_excess:+.3f} ({r.z_depth:+.1f})" for r in c) + " |")
# ---------- A3 cosine ----------
cv = load("expR57_census_cosine_haar_p999_200.csv")
if cv is not None:
    c = counts(cv); L.append("\n## A3. Cosine census (geodesic on L2-normalized centroids; Haar x p99.9; 200 replicates)\n")
    L.append(f"Vision: sign-negative {c['sign']}/72; genuine {c['gen']}/72; BH {c['gen_bh']}/72; ImageNet+CIFAR-100 BH {c['top_bh']}/24; other four BH {c['rest_bh']}/48.")
    if rec is not None:
        a = cv.set_index(["model","dataset"]).genuine_bh; b = rec.set_index(["model","dataset"]).genuine_bh; both = a.index.intersection(b.index)
        L.append(f"Verdict agreement with the Euclidean record (BH-genuine): {int((a[both]==b[both]).sum())}/{len(both)} cells.")
    by = {(r.model, r.dataset): r for r in cv.itertuples()}
    L.append("DINOv2 on ImageNet under cosine: " + "; ".join(f"{NM[m]} {by[(m,'imagenet')].excess:+.3f} (r {int(by[(m,'imagenet')].r_above)}, p {by[(m,'imagenet')].p_left:.3f}, {'G' if by[(m,'imagenet')].genuine_bh else 'not genuine'})" for m in ["dinov2_s","dinov2_b","dinov2_l","dinov2_g"]))
ct = load("expR57_text_cosine_haar_p999_200.csv")
if ct is not None: L.append(f"Text under cosine: genuine {int(ct.genuine.sum())}/15 (BH {int(ct.genuine_bh.sum())}): {', '.join(ct[ct.genuine_bh].model)}.")
# ---------- A4 tree map ----------
tm = R/"expR58_treemap_cutfree_summary.csv"
if tm.exists():
    s = pd.read_csv(tm); L.append("\n## A4. Tree map with and without a cut (DINOv2-B/L/G vs block / within block)\n")
    L.append("| dataset | configuration | ARI at cut | cophenetic corr. | triplet agreement |"); L.append("|---|---|---|---|---|")
    for r in s.itertuples():
        L.append(f"| {r.dataset} | {r.metric}-{r.linkage} | {r.ari_cut_big_vs_block:.2f} / {r.ari_cut_within_block:.2f} | {r.coph_corr_big_vs_block:.2f} / {r.coph_corr_within_block:.2f} | {r.triplet_agree_big_vs_block:.2f} / {r.triplet_agree_within_block:.2f} |")
OUTMD.write_text("\n".join(L)+"\n"); print(f"memo written: {OUTMD} ({len(L)} lines)")
