#!/usr/bin/env python3
"""V3_OUTLINE.md: the claim list of the author's brief (2026-09-18) with the ICLR margin line of the compiled v3 PDF where each
claim landed (pdftotext -layout keeps the margin numbers). Usage: python make_v3_outline.py ICLR2027/main_iclr2027_v3.pdf"""
import re, subprocess, sys, json
pdf = sys.argv[1]
txt = subprocess.run(["pdftotext", "-layout", "-l", "12", pdf, "-"], capture_output=True, text=True).stdout
numbered = []; last = None
for l in txt.split("\n"):
    m = re.match(r"\s*(\d{3})\s+(.*)", l)
    if m: last = int(m.group(1)); numbered.append((last, m.group(2)))
    elif l.strip():
        if re.fullmatch(r"\s*\d{3}\s*", l): last = int(l.strip()); continue
        numbered.append((last, l.strip()))
def find(phrase):
    norm = lambda s: re.sub(r"[^a-z0-9]", "", s.lower().replace("ﬁ", "fi").replace("ﬂ", "fl"))
    target = norm(phrase)
    for i in range(len(numbered)):
        if target in norm("".join(t for _, t in numbered[i:i + 3])): return numbered[i][0]
    return None
F = json.load(open("rebuttal/results/phaseE_v3_fills.json"))
SEC = [("1 Introduction (verbatim, with Figure 1)", [("the premise and the three confounds", "Why is the shadow low?"), ("the instrument and the three-part answer", "We build the instrument that reads")]),
       ("2 Related Work (verbatim)", [("network science, representation analyses, convergence program", "Reading δ against a matched reference has precedent")]),
       ("3.1 Background: Gromov δ", [("verbatim paragraph, Eq. 1 (pairings)", "Tree-likeness is measured on quadruples"), ("Definition 1 (four-point defect)", "Definition 1 (four-point defect)")]),
       ("3.2 Estimation and normalization", [("verbatim paragraph, Eq. 2", "Three steps turn"), ("Definition 2 (reading of record)", "Definition 2 (reading of record)"), ("Lemma 1 (range bound)", "Lemma 1 (range bound)"), ("Corollary 1 (dimension confound)", "Corollary 1 (dimension confound)"), ("Remark: spectrum and statistic confounds", "An anisotropic spectrum changes the effective dimension"), ("calibration on reference geometries (Table 3 of the brief)", "The calibration on reference geometries confirms the bound")]),
       ("3.3 Spectrum-matched null, excess and genuineness", [("Definition 3 (Haar null)", "Definition 3 (Haar null)"), ("why Haar and not Gaussian coefficients", "Gaussian coefficients reproduce the spectrum only in expectation"), ("Definition 4 (excess), Eq. 3", "Definition 4 (excess)"), ("rank and left-tail p, Eq. 4, K = 200", "The primary evidence is the rank of the reading"), ("Definition 5 (genuine), Eq. 5", "Definition 5 (genuine)"), ("clustered structure vs tree-like; Figure 2 cited", "A negative genuine excess certifies clustered structure")]),
       ("3.4 Depth test", [("Definition 6 (hub null and excess B)", "Definition 6 (hub null and excess B)"), ("Definition 7 (matched star)", "Definition 7 (matched star)"), ("Eq. 6, certification at z ≤ −2", "certified as more hierarchical than a star"), ("the star caveat", "The test is needed because of the star caveat"), ("validity measured in §5.3", "The false-alarm rate and the power of the test are measured on real clouds")]),
       ("3.5 Comparing trees across models", [("dendrograms, three measures, degeneracy criterion, calibrated local agreement", "Each model's hierarchy is a dendrogram over the shared class centroids")]),
       ("3.6 Projection and tasks", [("the map, the two tasks, three readouts", "A parameter-free map centers the features")]),
       ("4 Experimental Setup", [("models and the compact panel", "Twelve vision backbones form the census"), ("datasets, cells, two levels", "The vision census reads six class sets"), ("extraction", "Vision backbones give the encoder"), ("replicates, seeds, budgets, BH, frames, star seeds", "Every cell is read against 200 Haar replicates")]),
       ("5.1 The premise at the sample level", [(f"not genuine in {F['SL_WITHIN']} of 24; at most {F['SL_FRAC_HI']}% below the null, largest for DINOv2-G on CIFAR-100; genuine cells are the DINOv2 family (Table 4 of the brief)", "The premise does not survive calibration")]),
       ("5.2 Clustered structure at the class level", [(f"{F['NEG_COUNT']}/72 negative, 49/72 genuine (Table 1, Figure 3)", "Almost every cell is below its null"), (f"18/24 on ImageNet and CIFAR-100; {F['R11_LO']}–{F['R11_HI']} under joint sensitivity", "The count survives resampling"), ("every family; ViT-T on DTD only; flat datasets; class-count control; two ResNets", "The structure belongs to no single family"), (f"ImageNet excess {F['NULLU_LO']}–{F['NULLU_HI']} null spreads (brief: 3–8; file: see report)", "The excess is small in absolute terms"), (f"the star caveat (synthetic star reaches {F['STAR_DEEP']})", "The star caveat"), ("neural collapse: ETF is the limit, hubs show it is not the whole story", "Neural collapse is the limit"), ("scale: DINOv2 deepens on CIFAR-10, weakly on CIFAR-100; no general trend", "one family only")]),
       ("5.3 Depth above the labelled clusters", [(f"certified 4/12 (ViT-S/B/L, DINOv2-L); the same four under the spectrum-matched-hub star (z {F['HAAR_Z_HI']} to {F['HAAR_Z_LO']}) (Figure 4, Tables 5–6 of the brief)", "Depth is certified in four of twelve"), (f"{F['FA_HAAR']} false alarms with randomized hubs; the four never fire at zero strength ({F['CERT_S0']})", "The test raises no false alarm on real clouds"), (f"clean implanted tree detected in almost none (power {F['POWER_S1']}); ratios {F['RATIO_LO']}–{F['RATIO_HI']} outside the synthetic sweep", "The test is weak at ImageNet"), ("eight 'not detected'; certified set shifts with the frame; CIFAR-100 outside the validated regime; isotropic star withdrawn; shrunk variant diagnostic only", "The eight other backbones are not detected"), (f"ViT-B augreg certified (z {F['AUG_Z']}) and WordNet-aligned ({F['AUG_RHO']})", "Leaf-label supervision can produce the depth"), (f"DeiT-B not certified, unaligned ({F['DEIT_RHO']}), recovers superclasses ({F['DEIT_ARI']}); label sets are not the explanation; alignment recipe-dependent", "But it does not guarantee it"), (f"MERU: same clustering, no detected depth, near-flat regime (radius·√c {F['MERU_RAD_LO']}–{F['MERU_RAD_HI']}; Lorentz/Euclidean {F['MERU_RATIO']})", "Imposing the geometry does not create detected depth")]),
       ("5.4 Whose tree", [(f"naive map isolates DINOv2 ({F['NAIVE_BIG']} vs {F['NAIVE_BLOCK']}): chaining artifact; DINO-B not in the island (Figure 5)", "The naive map manufactures an island"), (f"selected configuration {F['ARI_BIG']} vs {F['ARI_BLOCK']}; other admissible {F['ADM_LO']}–{F['ADM_HI']} vs {F['ADM_BLK_LO']}–{F['ADM_BLK_HI']}", "Controlling the cut leaves a moderate gap"), (f"cophenetic {F['COPH_BIG']} vs {F['COPH_BLOCK']}; triplets {F['TRIP_BIG']} vs {F['TRIP_BLOCK']} under cosine-average only", "The gap depends on the measure"), (f"angular tree: {F['TRIP_L_C']}/{F['TRIP_G_C']} cosine vs {F['TRIP_L_E']}/{F['TRIP_G_E']} Euclidean for DINOv2-L/G", "The self-supervised tree is angular"), (f"cosine census agrees in {F['AGREE']}/72", "The cosine census agrees with the Euclidean one"), (f"WordNet alignment: contrastive {F['RHO_CON_LO']}–{F['RHO_CON_HI']}, supervised {F['RHO_SUP_LO']}–{F['RHO_SUP_HI']}", "WordNet alignment follows supervision and recipe"), (f"DINOv2 {F['RHO_D2_LO']}–{F['RHO_D2_HI']}; supervision deepens on average, recipe-dependent; form and content anti-correlate", "DINOv2 is the least aligned and the most robust"), (f"not WordNet circularity: DBpedia three embedders genuine ({F['DBP_EXC_LO']} to {F['DBP_EXC_HI']}), sibling agreement {F['DBP_TRIP']}", "The recovery is not WordNet circularity"), (f"HierarCaps {F['HC_TRIP_LO']}–{F['HC_TRIP_HI']}", "The same reading holds on a four-level caption hierarchy"), (f"text census: {F['TEXT_GEN']}/15 genuine; GPT-2 S genuine (p {F['GPT2S_P']}), M not, L/XL under every reading", "The text census depends on recipe"), ("Pythia at every scale; OLMo-1B; embedders absent on class names, present on DBpedia; template and extraction move the fragile values only", "Pythia is genuine at every scale tested")]),
       ("5.5 What is shared is local and ordinal", [(f"calibrated mKNN {F['KNN_CAL']} and CKA {F['CKA_CAL']} over 66 pairs, all significant (Table 10 of the brief)", "Local agreement survives calibration"), ("Poincaré improves neither reading (the values are in Table 13); shared neighborhoods, model-specific metric", "improves neither reading")]),
       ("6 Implications for hyperbolic representation learning", [(f"Khrulkov rule (Eq. 7) assigns c from {F['C_LO']} (d = {F['D_LO']}) to {F['C_HI']} (d = {F['D_HI']}) to Gaussian clouds", "The raw reading cannot select a curvature"), ("calibrated reading predicts NC gain on four datasets and FS on three; depth predicts nothing (Table 11 of the brief)", "The calibrated reading predicts the zero-cost gain"), (f"cosine collects the self-supervised structure; Poincaré {F['GAIN_LO']} to {F['GAIN_HI']} pp only for contrastive VLMs; nothing on flat labels; sample-level tasks never benefit", "A zero-cost readout collects what is there"), ("what to measure before imposing curvature", "Measure before imposing")]),
       ("7 Conclusion and Limitations", [("the thesis sentence verbatim", "Read correctly, foundation models organize classes"), ("limitations (i)–(viii)", "The excess certifies structure beyond second moments")]),
       ("Statements", [("Reproducibility (anonymized repo, tool/)", "Every number in the paper is annotated"), ("Ethics", "involves no human subjects"), ("AI use (four items)", "we used generative AI tools for four tasks")])]
out = ["# V3_OUTLINE — the claim list of the brief and where each claim landed in `main_iclr2027_v3.pdf`", "", "Line numbers are the ICLR margin numbers of the compiled v3 PDF; every number in a claim is the fill read from its result file (`rebuttal/results/phaseE_v3_fills.json`). Table numbers in parentheses are the brief's; the file numbers them in citation order (Table 1 census, then Table 2 robustness, Table 3 calibration, ...).", ""]
missing = []
for sec, items in SEC:
    out.append(f"## {sec}"); out.append("")
    for claim, anchor in items:
        ln = find(anchor)
        if ln is None: missing.append(anchor)
        out.append(f"- line {ln if ln else '?'}: {claim}")
    out.append("")
open("ICLR2027/V3_OUTLINE.md", "w").write("\n".join(out)); print("V3_OUTLINE.md written; missing anchors:", missing)
