#!/usr/bin/env python3
"""Final pass, items 5-6: class-count sweep (expR60) and DBpedia (expR61) under the census of record -> §4 sentences,
Tables B3/A9 regenerated by their generators, numbers used in the text saved to phaseB_final_numbers.json for the sweep.
Run from the repo root after both result files exist."""
import json
import pandas as pd
R = 'rebuttal/results/'
c = pd.read_csv(R + 'expR60_c_sweep_record.csv'); db = pd.read_csv(R + 'expR61_dbpedia_record.csv')
def agg(m, C, mode, f): g = c[(c.model == m) & (c.C == C) & (c['mode'] == mode)]; return float(g[f].mean()), int((g.p_left <= 0.05).sum()), len(g)
er, _, _ = agg('dinov2_l', 50, 'random', 'excess'); ec, _, _ = agg('dinov2_l', 50, 'coherent', 'excess')
# raw d999 vs C (random subsets): monotone rise?
rise = [agg('dinov2_l', C, 'random', 'delta_999')[0] for C in (10, 20, 50, 100, 200, 500, 1000)]
rises = all(b > a for a, b in zip(rise, rise[1:]))
g1000 = c[(c.model == 'dinov2_g') & (c.C == 1000)].iloc[0]; g500 = c[(c.model == 'dinov2_g') & (c.C == 500) & (c['mode'] == 'random')]
g_all_below = all(agg('dinov2_g', C, 'random', 'excess')[1] == agg('dinov2_g', C, 'random', 'excess')[2] for C in (10, 20, 50, 100, 200, 500, 1000))
CS = (10, 20, 50, 100, 200, 500)
# per model: largest C such that random subsets carry more excess (more negative) than coherent ones at every C' <= C
def thr(m):
    t = 0
    for C in CS:
        if agg(m, C, 'random', 'excess')[0] < agg(m, C, 'coherent', 'excess')[0]: t = C
        else: break
    return t
THR = {m: thr(m) for m in ('dinov2_l', 'dinov2_g', 'clip_l')}
c10 = {m: agg(m, 10, 'random', 'excess')[0] for m in ('dinov2_l', 'dinov2_g', 'clip_l')}
nc_more = all(agg(m, C, 'random', 'nc_adv_pp')[0] > agg(m, C, 'coherent', 'nc_adv_pp')[0] for m in ('dinov2_l', 'dinov2_g', 'clip_l') for C in CS)
print(f"Dv2-L C=50 excess random {er:+.4f} coherent {ec:+.4f}; d999 vs C {['%.3f'%x for x in rise]} rises={rises}; Dv2-G C=1000 exc {g1000.excess:+.4f} r={g1000.r_above} p={g1000.p_left:.3f}, C=500 r={list(g500.r_above)}; all Dv2-G below: {g_all_below}; random-more thresholds {THR}; C=10 random {c10}; NC random>coherent everywhere: {nc_more}")
lo, hi = db.excess.max(), db.excess.min(); rmin = int(db.r_above.min()); pmax = float(db.p_left.max()); allbh = bool(db.genuine_bh.all())
print(f"DBpedia record: excess {lo:+.4f}..{hi:+.4f}; r min {rmin}; p max {pmax:.3f}; BH all {allbh}; sup-exp14: {list(pd.read_csv(R+'exp14_dbpedia.csv').excess.round(3))}")
json.dump(dict(dv2l_c50_random=er, dv2l_c50_coherent=ec, d999_rises=bool(rises), dv2g_c1000_excess=float(g1000.excess), dv2g_c1000_r=int(g1000.r_above), dv2g_c1000_p=float(g1000.p_left),
               dv2g_all_below=bool(g_all_below), random_more_thresholds=THR, c10_random_excess=c10, nc_random_more_everywhere=bool(nc_more),
               dbpedia_excess_lo=float(lo), dbpedia_excess_hi=float(hi), dbpedia_r_min=rmin, dbpedia_p_max=pmax, dbpedia_bh_all=allbh),
          open(R + 'phaseB_final_numbers.json', 'w'), indent=1)

p = 'ICLR2027/iclr2027/main_iclr2027.tex'; T = open(p).read()
def rep(old, new):
    global T
    assert T.count(old) == 1, f"{T.count(old)} matches: {old[:90]!r}"; T = T.replace(old, new)
i = T.find("\\paragraph{Hierarchy depth, not class count.}"); j = T.find("\n\n", i); assert i > 0
assert nc_more, "NC exploitability contrast no longer holds everywhere; rewrite by hand"
NMm = {'dinov2_l': 'DINOv2-L', 'dinov2_g': 'DINOv2-G', 'clip_l': 'CLIP-L'}
def thr_s(m):
    t = THR[m]; return f"{NMm[m]} at every $C$" if t == 500 else f"{NMm[m]} up to $C{{=}}{t}$"
allC = [m for m in THR if THR[m] == 500]; part = [m for m in THR if THR[m] < 500]
where = ", ".join([thr_s(m) for m in allC] + [thr_s(m) for m in part])
conv = (" and for " + "/".join(NMm[m].replace('DINOv2-', '') for m in part) + " the two compositions converge at larger $C$") if part else ""
c10lo, c10hi = max(c10.values()), min(c10.values())
if g_all_below and g1000.p_left <= 0.05:
    g_s = f"DINOv2-G stays below its null at every $C$ up to 1000 (excess ${g1000.excess:+.3f}$, $r{{=}}{g1000.r_above}$), where the supremum had placed it at the null: that exception was a supremum artifact."
else:
    g_s = f"DINOv2-G reaches its null only at $C{{=}}1000$ (excess ${g1000.excess:+.3f}$, $p{{=}}{g1000.p_left:.2f}$) under the record."
T = T[:i] + (f"\\paragraph{{Hierarchy depth, not class count.}} At fixed $C$, random ImageNet subsets, which span the full hierarchy, are more exploitable than WordNet-coherent sibling subsets, an effectively flat concept set, and carry more beyond-null structure at small $C$ ({where}; DINOv2-L at $C{{=}}50$ under the record: ${er:+.3f}$ vs ${ec:+.3f}$){conv} (Table~\\ref{{tab:b3-csweep}}). Random subsets still score ${c10lo:+.2f}$ to ${c10hi:+.2f}$ at $C{{=}}10$, so MNIST's flat verdict is not a class-count artifact. " + g_s + " % expR60_c_sweep_record.csv, exp19_c_sweep.csv") + T[j:]
rr = "every replicate above the real value" if rmin == 200 else f"$r\\ge{rmin}$ of 200"
rep("the sentence embedders show genuine excess ($-0.020$ to $-0.028$ under the original supremum reading; Appendix~\\ref{app:tables})",
    f"the sentence embedders show beyond-null excess under the record (${lo:+.3f}$ to ${hi:+.3f}$, {rr}; Table~\\ref{{tab:a9}})")
rep("expR57_text_cosine_haar_p999_200.csv, exp14, exp18b_text_anisotropy.csv", "expR57_text_cosine_haar_p999_200.csv, expR61_dbpedia_record.csv, exp18b_text_anisotropy.csv")
open(p, 'w').write(T); print("t5 applied")
