#!/usr/bin/env python3
"""Parallel version v2 (style of Groger et al. 2026 / Huh et al. 2024): fills phaseE_paper_v2.tex.tmpl with the SAME fills as the
frozen v1 (rebuttal/results/phaseE_fills.json, written by phaseE_final.py) and writes ICLR2027/iclr2027/main_iclr2027_v2.tex =
v1 preamble (+ tcolorbox/amsthm and the shaded-box definitions) + the filled v2 body + the v1 tail (statements, bibliography and the
appendix, copied verbatim from phaseE_paper.tex.tmpl so both versions share every table, figure and result file). Never touches
main_iclr2027.tex. Run from the repo root after phaseE_final.py."""
import json, re
R = 'rebuttal/results/'; S = 'rebuttal/scripts/'; P1 = 'ICLR2027/iclr2027/main_iclr2027.tex'; P2 = 'ICLR2027/iclr2027/main_iclr2027_v2.tex'
F = json.load(open(R + 'phaseE_fills.json'))
body = open(S + 'phaseE_paper_v2.tex.tmpl').read()
for k, v in F.items(): body = body.replace("{{" + k + "}}", v)
left = re.findall(r"\{\{[A-Z0-9_]+\}\}", body); assert not left, left
v1t = open(S + 'phaseE_paper.tex.tmpl').read(); tail = v1t[v1t.index("\\subsubsection*{Ethics Statement}"):]
for k, v in F.items(): tail = tail.replace("{{" + k + "}}", v)
assert not re.findall(r"\{\{[A-Z0-9_]+\}\}", tail)
T1 = open(P1).read(); pre = T1[:T1.index("\\begin{abstract}")]
assert "\\usepackage{tcolorbox}" not in pre
pre = pre.replace("\\usepackage{array}\n", "\\usepackage{array}\n\\usepackage{amsthm}\n\\usepackage{tcolorbox}\n\\usepackage{caption}\n", 1)
pre = pre.replace("\\begin{document}\n", "\\theoremstyle{definition}\n\\newtheorem{definition}{Definition}\n"
                  "\\newtcolorbox{shaded}{colback=gray!7, colframe=black!22, boxrule=0.4pt, arc=1.5pt, left=5pt, right=5pt, top=3pt, bottom=3pt, before skip=5pt, after skip=5pt}\n"
                  "% v2: parallel version restyled after Groger et al. (2026) and Huh et al. (2024); generated by rebuttal/scripts/phaseE_v2.py. The submission file is main_iclr2027.tex.\n\\begin{document}\n", 1)
assert "\\newtcolorbox{shaded}" in pre and "\\usepackage{amsthm}" in pre
open(P2, 'w').write(pre + body + tail); print("v2 written ->", P2)
